config/routes.rb
Rails.application.routes.draw do

  use_doorkeeper
  devise_for :users

  namespace :api do
  	namespace :v1 do
  		resources :users, only: [:index, :update]
  		post '/users/prova' => 'users#prova'
  		post '/transactions/sell' => 'transactions#sell'
  		post '/transactions/buy' => 'transactions#buy'
    	post :signup, to: 'signup#index'
  	end
  end

  match "/404", :to => "errors#not_found", :via => :all
  match "/500", :to => "errors#internal_server_error", :via => :all

  get 'transactions/index' => 'transactions#index'
  get 'transactions/transactions' => 'transactions#transactions'
  get 'transactions' => 'transactions#index'

  get 'transactions/search' => 'transactions#search', as: :transactions_search #used by the ransack page

  get 'users/index' => 'users#index', as: :users_index
  get 'users/all' => 'users#all_users', as: :users_all

  get 'user/all_transactions' => 'users#all_transactions', as: :user_transactions
  get 'user/purchases' => 'users#purchases', as: :user_purchases
  get 'user/sales' => 'users#sales', as: :user_sales
  get 'user/search' => 'users#search', as: :user_search

  get 'user/download_sells' => 'users#by_seller', as: :user_sells
  get 'user/download_purchases' => 'users#by_buyer', as: :user_buys
  get 'user/download_all' => 'users#all', as: :user_alltransactions

  get 'user/:id' => 'users#show', as: :user_show
  
  get 'transactions/accept/:id' => 'transactions#accept', as: :transaction_accept
  get 'transactions/reject/:id' => 'transactions#reject', as: :transaction_reject
  post 'transactions/create' => 'transactions#create', as: :transaction_create
  get 'transactions/upload' => 'transactions#upload', as: :transaction_upload

  get 'transactions/all' => 'transactions#all', as: :transactions_all
  get 'transactions/toapprove' => 'transactions#toapprove', as: :transactions_toapprove
  get 'transactions/rejected' => 'transactions#rejected', as: :transactions_rejected
  get 'transactions/accepted' => 'transactions#accepted', as: :transactions_accepted
  get 'transactions/incomplete' => 'transactions#incomplete', as: :transactions_incomplete


  get 'transactions/:id' => 'transactions#show', as: :transaction_show
  get 'transactions/:id/edit' => 'transactions#edit', as: :transaction_edit
  match 'transactions/:id/update' => 'transactions#update', as: :transaction_update, :via => [:post, :patch]

  get "/uploads/transaction/:mount/example/:id/:basename.:extension", :controller => "images", :action => "download"

  authenticated :user do
    root :to => "transactions#index"
  end

  unauthenticated :user do
    devise_scope :user do
      get "/" => "devise/sessions#new"
    end
  end

  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates_format_of :email, with: /\A([^\s]+)((?:[-a-z0-9]\.)[a-z]{2,})\z/i

  has_many :sales, :class_name => 'Transaction', :foreign_key => 'seller_id'
  has_many :purchases, :class_name => 'Transaction', :foreign_key => 'buyer_id'

  def is_admin?
  	self.is_admin
  end

  def self.find_by_email(email)
  	where(:email => email).first
  end

  def full_name
    return "#{name} #{surname}" if !name.nil? or !surname.nil? 
    return "Unnamed"
  end

  private 

  # Whitelist the Transaction model attributes for sorting.
  #
  #
  def self.ransortable_attributes(auth_object = nil)
    ['email', 'name', 'surname']
  end

  # Whitelist the Transaction model attributes for search, except +password_digest+,
  #
  def self.ransackable_attributes(auth_object = nil)
    ransortable_attributes
  end

  def self.search(term)
    where('LOWER(email) LIKE :term', term: "%#{term.downcase}%")
  end

end

app/controllers/api/v1/users_controller.rb
class Api::V1::UsersController < Api::V1::BaseController

  def index
    users = User.all
    
    #render json: { users: users.to_json }, each_serializer: UserSerializer
    render json: { users: users.to_json }
  end

  def update
    user = User.find(params[:id])
    if user.update(update_params)
      #render json: user, serializer: UserSerializer, status: 200
      render json: user.to_json, status: 200
    else
      render json: { errors: user.errors }, status: 422
    end
  end

  def prova
    prova = params[:prova]
    logger.debug prova
    prova2 = params[:prova2]
    logger.debug prova2

    render json: { users: current_user.to_json }
  end

private

  def update_params
    params.permit(:email, :password)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	def sales
  	respond_to do |format|
      format.html
      format.json { render json: UserTransactionDatatable.new(view_context, {:status => params[:status], :id => params[:id]}) }
    end
  end

  def all_transactions
  	respond_to do |format|
      format.html
      format.json { render json: UserTransactionDatatable.new(view_context, {:status => params[:status], :id => params[:id]}) }
    end
  end

  def purchases
  	respond_to do |format|
      format.html
      format.json { render json: UserTransactionDatatable.new(view_context, {:status => params[:status], :id => params[:id]}) }
    end
  end

  def show
  	if !params[:id].nil?
	  	@user = User.find(params[:id])
	  	if current_user.is_admin? or current_user == @user
	  	  render :show
	  	else
	  	  redirect_to user_show_url(current_user), alert: 'Unauthorized to look at the page of the user'
	  	end
	  else
	  	redirect_to user_show_url(current_user)
	  end
  end

  def index
  	if current_user
  	  if current_user.is_admin? 
  	  	render 'index'
  	  else 
  	  	redirect_to user_show_url(current_user), alert: 'Not Allowed to look at the page'	
  	  end
  	else
  	  redirect_to new_user_session_url 
  	end
  end

  
  def by_seller
  	if !params[:id].nil?
  		@user = User.find(params[:id])
	  	if current_user.is_admin? or current_user == @user
	  	  @transactions = Transaction.by_seller(params[:id])
	  	  respond_to do |format|
					format.csv { send_data @transactions.to_csv }
					format.xls # { send_data @products.to_csv(col_sep: "\t") }
				end
	  	else
	  	  redirect_to user_show_url(current_user), alert: 'Cannot download the data'
	  	end
	  else
	  	redirect_to user_show_url(current_user)
	  end
  end

  def by_buyer
  	if !params[:id].nil?
  		@user = User.find(params[:id])
	  	if current_user.is_admin? or current_user == @user
	  	  @transactions = Transaction.by_buyer(params[:id])
	  	  respond_to do |format|
					format.csv { send_data @transactions.to_csv }
					format.xls # { send_data @products.to_csv(col_sep: "\t") }
				end
	  	else
	  	  redirect_to user_show_url(current_user), alert: 'Cannot download the data'
	  	end
	  else
	  	redirect_to user_show_url(current_user)
	  end
  end

  def all
  	if !params[:id].nil?
  		@user = User.find(params[:id])
	  	if current_user.is_admin? or current_user == @user
	  	  @transactions = Transaction.by_user(params[:id])
	  	  respond_to do |format|
					format.csv { send_data @transactions.to_csv }
					format.xls # { send_data @products.to_csv(col_sep: "\t") }
				end
	  	else
	  	  redirect_to user_show_url(current_user), alert: 'Cannot download the data'
	  	end
	  else
	  	redirect_to user_show_url(current_user)
	  end
  end

  def all_users
  	respond_to do |format|
      format.html
      format.json { render json: UsersDatatable.new(view_context) }
    end
  end

  def search
    respond_to do |format|
      format.html
      format.json { @users = User.search(params[:term]) }
    end
  end


end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/all.xls.erb
<%= render "transactions/table" %>

app/views/users/by_buyer.xls.erb
<%= render "transactions/table" %>

app/views/users/by_seller.xls.erb
<%= render "transactions/table" %>

app/views/users/index.html.erb
<div class="row">
  <div class="col-sm-12 col-md-12 col-lg-12"><h1>Users</h1></div>
	  <div class="col-sm-12 col-md-12 col-lg-12">
			<table id="users-table" class="display table table-striped hover" cellspacing="0" width="100%" data-source="<%= users_all_path(id: current_user.id, format: :json) %>">
		        <thead>
		            <tr>
		                <th>Id</th>
		                <th>Email</th>
		                <th>Name</th>
		                <th>Surname</th>
		            </tr>
		        </thead>
		        <tfoot>
		            <tr>
		                <th>Id</th>
		                <th>Email</th>
		                <th>Name</th>
		                <th>Surname</th>
		            </tr>
		        </tfoot>
			</table>
		</div>
</div>

app/views/users/show.html.erb
<div class="row">
  <div class="col-sm-12 col-md-12 col-lg-12"><h1>User Profile</h1></div>
  <div class="col-sm-12 col-md-12 col-lg-12">
  	<div class="card card-block">
      	<h3 class="card-title">Bio</h3>
      	<p class="card-text"><strong>Name:</strong> <%= @user.try(:name) %> </p>
      	<p class="card-text"><strong>Surname:</strong> <%= @user.try(:surname) %> </p>
      	<p class="card-text"><strong>Email:</strong> <%= @user.try(:email) %></p>
      	<% if current_user == @user %>
       	  <%= link_to "Edit Profile", edit_user_registration_path, class: 'btn btn-primary pull-xs-right' %>
        <% end %>
	</div>
  	 
  </div>
</div>

<div class="row">
	<div class="col-sm-12 col-md-12 col-lg-12">
		<h3>Transactions</h3>
		<div class="col-sm-12 col-md-12 col-lg-12">
			<!-- Nav tabs -->
		<ul class="nav nav-tabs" id="nav-admin" role="tablist">
		  <li class="nav-item">
		    <a class="nav-link active" data-toggle="tab" data-val="all" href="#all" role="tab">All</a>
		  </li>
		  <li class="nav-item">
		    <a class="nav-link" data-toggle="tab" data-val="sells" href="#sells" role="tab">Sales</a>
		  </li>
		  <li class="nav-item">
		    <a class="nav-link" data-toggle="tab" data-val="buys" href="#buys" role="tab">Purchases</a>
		  </li>
		</ul>


		<div class="tab-content">
		  <div class="tab-pane fade in active" id="all" role="tabpanel">
		  	<p class="pull-xs-right">
  				Download:
  				<%= link_to "CSV", user_alltransactions_path(id: @user.id, format: "csv") %> |
  				<%= link_to "Excel", user_alltransactions_path(id: @user.id, format: "xls") %>
			</p>
		  	<table id="all-users" class="display table table-striped hover" cellspacing="0" width="100%" data-source="<%= user_transactions_path(status: 'ALL', id: @user.id,format: :json) %>">
		        <thead>
		            <tr>
		                <th>Id</th>
		                <th>Seller</th>
		                <th>Buyer</th>
		                <th>Timestamp</th>
		                <th>Amount</th>
		            </tr>
		        </thead>
		        <tfoot>
		            <tr>
		                <th>Id</th>
		                <th>Seller</th>
		                <th>Buyer</th>
		                <th>Timestamp</th>
		                <th>Amount</th>
		            </tr>
		        </tfoot>
			</table>
		  </div>
		  <div class="tab-pane fade" id="sells" role="tabpanel">
		  	<p class="pull-xs-right">
  				Download:
  				<%= link_to "CSV", user_sells_path(id: @user.id, format: "csv") %> |
  				<%= link_to "Excel", user_sells_path(id: @user.id, format: "xls") %>
			</p>
		  	<table id="sells-table" class="display table table-striped hover" cellspacing="0" width="100%" data-source= <%= user_sales_path(status: 'SELLER', id: @user.id, format: :json) %> >
		        <thead>
		            <tr>
		                <th>Id</th>
		                <th>Seller</th>
		                <th>Buyer</th>
		                <th>Timestamp</th>
		                <th>Amount</th>
		            </tr>
		        </thead>
		        <tfoot>
		            <tr>
		                <th>Id</th>
		                <th>Seller</th>
		                <th>Buyer</th>
		                <th>Timestamp</th>
		                <th>Amount</th>
		            </tr>
		        </tfoot>
			</table>
		  </div>
		  <div class="tab-pane fade" id="buys" role="tabpanel">
		  	<p class="pull-xs-right">
  				Download:
  				<%= link_to "CSV", user_buys_path(id: @user.id, format: "csv") %> |
  				<%= link_to "Excel", user_buys_path(id: @user.id, format: "xls") %>
			</p>
		  	<table id="buyers-table" class="display table table-striped hover" cellspacing="0" width="100%" data-source= <%= user_purchases_path(status: 'BUYER', id: @user.id, format: :json) %>>
		        <thead>
		            <tr>
		                <th>Id</th>
		                <th>Seller</th>
		                <th>Buyer</th>
		                <th>Timestamp</th>
		                <th>Amount</th>
		            </tr>
		        </thead>
		        <tfoot>
		            <tr>
		                <th>Id</th>
		                <th>Seller</th>
		                <th>Buyer</th>
		                <th>Timestamp</th>
		                <th>Amount</th>
		            </tr>
		        </tfoot>
			</table>
		  </div>
		</div>
	</div>
</div>