config/routes.rb
Rails.application.routes.draw do

  use_doorkeeper
  devise_for :users

  namespace :api do
  	namespace :v1 do
  		resources :users, only: [:index, :update]
  		post '/users/prova' => 'users#prova'
  		post '/transactions/sell' => 'transactions#sell'
  		post '/transactions/buy' => 'transactions#buy'
    	post :signup, to: 'signup#index'
  	end
  end

  match "/404", :to => "errors#not_found", :via => :all
  match "/500", :to => "errors#internal_server_error", :via => :all

  get 'transactions/index' => 'transactions#index'
  get 'transactions/transactions' => 'transactions#transactions'
  get 'transactions' => 'transactions#index'

  get 'transactions/search' => 'transactions#search', as: :transactions_search #used by the ransack page

  get 'users/index' => 'users#index', as: :users_index
  get 'users/all' => 'users#all_users', as: :users_all

  get 'user/all_transactions' => 'users#all_transactions', as: :user_transactions
  get 'user/purchases' => 'users#purchases', as: :user_purchases
  get 'user/sales' => 'users#sales', as: :user_sales
  get 'user/search' => 'users#search', as: :user_search

  get 'user/download_sells' => 'users#by_seller', as: :user_sells
  get 'user/download_purchases' => 'users#by_buyer', as: :user_buys
  get 'user/download_all' => 'users#all', as: :user_alltransactions

  get 'user/:id' => 'users#show', as: :user_show
  
  get 'transactions/accept/:id' => 'transactions#accept', as: :transaction_accept
  get 'transactions/reject/:id' => 'transactions#reject', as: :transaction_reject
  post 'transactions/create' => 'transactions#create', as: :transaction_create
  get 'transactions/upload' => 'transactions#upload', as: :transaction_upload

  get 'transactions/all' => 'transactions#all', as: :transactions_all
  get 'transactions/toapprove' => 'transactions#toapprove', as: :transactions_toapprove
  get 'transactions/rejected' => 'transactions#rejected', as: :transactions_rejected
  get 'transactions/accepted' => 'transactions#accepted', as: :transactions_accepted
  get 'transactions/incomplete' => 'transactions#incomplete', as: :transactions_incomplete


  get 'transactions/:id' => 'transactions#show', as: :transaction_show
  get 'transactions/:id/edit' => 'transactions#edit', as: :transaction_edit
  match 'transactions/:id/update' => 'transactions#update', as: :transaction_update, :via => [:post, :patch]

  get "/uploads/transaction/:mount/example/:id/:basename.:extension", :controller => "images", :action => "download"

  authenticated :user do
    root :to => "transactions#index"
  end

  unauthenticated :user do
    devise_scope :user do
      get "/" => "devise/sessions#new"
    end
  end

  
end

app/controllers/api/v1/transactions_controller.rb
class Api::V1::TransactionsController < Api::V1::BaseController

  def sell
    #TODO: Check if picture exists 
    #TODO: Se la transazione esiste già allora dobbiamo fare l'update o impedirlo 
    seller = User.find_by_email(seller_params[:seller])
    buyer = User.find_by_email(seller_params[:buyer])
    status = 200
    if !seller.nil? and !buyer.nil?
      transaction = Transaction.already_present?(seller, buyer, seller_params[:transactiontime])
      if !transaction.nil? and !transaction.sell_completed?
        status = 200
        transaction.pictureBW = seller_params[:pictureBW]
        transaction.share1 = seller_params[:share1]
        transaction.pictureOriginal = seller_params[:pictureOriginal]
      else
        status = 201
        transaction = Transaction.new()
        transaction.seller = seller
        transaction.buyer = buyer
        transaction.transactiontime = seller_params[:transactiontime]
        transaction.pictureBW = seller_params[:pictureBW]
        transaction.share1 = seller_params[:share1]
        transaction.pictureOriginal = seller_params[:pictureOriginal]
      end

      reply(transaction, status)

    else
      render json: { errors: 'Transaction creation failed' }, status: 422
    end
  end

  def buy
    seller = User.find_by_email(buyer_params[:seller])
    buyer = User.find_by_email(buyer_params[:buyer])
    status = 200
    if !seller.nil? and !buyer.nil?
      transaction = Transaction.already_present?(seller, buyer, buyer_params[:transactiontime])
      if !transaction.nil? and !transaction.buy_completed?
        status = 200
        transaction.share2 = buyer_params[:share2] if !buyer_params[:share2].blank?
      else
        status = 201
        transaction = Transaction.new()
        transaction.seller = seller
        transaction.buyer = buyer
        transaction.transactiontime = buyer_params[:transactiontime]
        transaction.share2 = buyer_params[:share2] if !buyer_params[:share2].blank?
      end

      reply(transaction, status)

    else
      render json: { errors: 'Transaction creation failed' }, status: 422
    end
  end

private

  def seller_params
    params.permit(:seller, :buyer, :transactiontime, :pictureBW, :share1, :pictureOriginal, :amount, :access_token)
  end

  def buyer_params
    params.permit(:seller, :buyer, :transactiontime, :share2, :amount, :access_token)
  end

  def reply(transaction, status)
    if transaction.save
      DecryptTransactionJob.perform_later(transaction) if transaction.should_decrypt?
      render json: { transaction_id: transaction.id }, status: status
    else
      render json: { errors: transaction.errors }, status: 422
    end
  end

end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  require 'base64'
  require 'date'


  def index
    unless current_user.is_admin?
      redirect_to user_show_url(current_user)
    end
  end

  def edit
    if current_user.is_admin? and !params[:id].blank?
    	@transaction = Transaction.find(params[:id])
    else
    	redirect_to user_show_url(current_user)
    end
    
  end

  def update
  	amount = params[:transaction][:amount].to_d
  	@transaction = Transaction.find(params[:id])
  	
  	if !amount.blank? and amount > 0
  	  @transaction.amount = amount
  	
  	  if @transaction.save!
        redirect_to transaction_show_url(@transaction), notice: "Transaction Updated"
      else
    	  redirect_to transaction_edit_url(@transaction), alert: "Transaction cannot be updated"
      end
    else
    	redirect_to transaction_edit_url(@transaction), alert: "You cannot set the transaction amount to 0.0"
    end
  end

  def create
    uploaded_pics = params[:file]

    if !uploaded_pics.nil?
      uploaded_pics.each do |index,pic|
        regex = '^Pgs+\s+[a-zA-Z0-9]*_\d_\d+_[a-zA-Z0-9]+_PBS_[a-zA-Z]+'
        matcher = Regexp.new(regex,Regexp::IGNORECASE)

        original_filename = pic.original_filename
        filename = pic.original_filename.split('.')[0]

        if matcher.match(filename)
          info = filename.split('_')
          user_email = info[0].gsub('Pgs ','').concat("_" + info[1])
          timestamp = DateTime.strptime(info[2],"%d%m%Y%H%M%S")
          photo_type = info[3].downcase
          
          if info[5].downcase.include? 'buyer'
            transaction_type = 'buyer'
          else
            transaction_type = 'seller'
          end

          #debugger

          # Se l'utente esiste
          # TODO: Rimane il problema del mancato match in alcuni casi
          user = User.where(:email => user_email).or(User.where(:email => user_email+'@alphaplus.com')).first
          transaction = Transaction.where(:transactiontime => timestamp).first

          user.nil? ? user = create_fake_user(user_email) : user = user
          transaction.nil? ? transaction = Transaction.new : transaction = transaction

          case photo_type
          when 'gray'
            transaction.pictureOriginal = create_Base64_image(pic) if transaction.pictureOriginal.blank? and transaction_type == 'seller'
            transaction.pictureBW = create_Base64_image(pic) if transaction.pictureBW.blank? and transaction_type == 'buyer'
          when 'share1'
            transaction.share1 = create_Base64_image(pic) if transaction.share1.blank? and transaction_type == 'buyer'
          when 'share2'
            transaction.share2 = create_Base64_image(pic) if transaction.share2.blank? and transaction_type == 'seller'
          end
          
          if transaction.changed?
            transaction.seller = user if transaction_type == 'seller'
            transaction.buyer = user if transaction_type == 'buyer'
            transaction.transactiontime = timestamp
            transaction.save
            DecryptTransactionJob.perform_later(transaction) if transaction.should_decrypt?
          end
          # else
          #   # Non esiste l'utente e quindi lo creo
          #   user = create_fake_user(user_email)

          #end

        #else
          # Torna un errore il file non ha il nome corretto
        end
      end
    end

    render json: { message: 'You have successfully uploded your images.' }
    
  end

  def upload
    unless current_user.is_admin?
      redirect_to user_show_url(@current_user), alert: "Access Denied"
    end
  end

  # TODO: Protect only current_user and !current_user.blank?
  def transactions
  	respond_to do |format|
      format.html
      format.json { render json: TransactionDatatable.new(view_context, {:status => params[:status]}) }
    end
  end

  def show
  	if !params[:id].blank?
  	  begin
  	  	@transaction = Transaction.includes(:seller, :buyer).find(params[:id])
        if current_user == @transaction.seller or current_user == @transaction.buyer or current_user.is_admin?
          return @transaction
        else
          redirect_to root_url, alert: "You're not supposed to view the Transaction"
        end
  	  rescue ActiveRecord::RecordNotFound
  	  	redirect_to root_url, alert: "The Transaction doesn't exists" 
  	  	return
  	  end
  	else
  	  redirect_to root_url, alert: "The Url is wrong"  
    end
  end

  #TODO: Clumsy code -- Please rewrite
  def accept
  	if current_user && current_user.is_admin?
  	  if !params[:id].blank?
  	    t = Transaction.find(params[:id])
  	    if t.is_completed? and t.have_amount?
  	    	if t.accept
  		  		redirect_to transaction_show_url(t), notice: "Transaction Accepted"
  	    	else
  		  		redirect_to transaction_show_url(t), alert: "Transaction cannot be accepted"
  				end
  			else
  				redirect_to transaction_show_url(t), alert: "Check if transaction is completed or if the amount is bigger than 0.0"
  	    end
  	  end
  	else
  		redirect_to root_url, alert: "Log in as an admin to perform action"
  	end
  end

  #TODO: Clumsy code -- Please rewrite
  def reject
  	if current_user && current_user.is_admin?
  		if !params[:id].blank?
  			t = Transaction.find(params[:id])
  			if t.is_completed? and t.have_amount?
  				if t.reject
  					redirect_to transaction_show_url(t), notice: "Transaction Rejected"
  				else
  					redirect_to transaction_show_url(t), alert: "Transaction cannot be accepted"
  				end
  			else
  				redirect_to transaction_show_url(t), alert: "Check if transaction is completed or if the amount is bigger than 0.0"
  			end
  		end
  	else
  		redirect_to root_url, alert: "Log in as an admin to perform action"
  	end
  end

  def all
    if current_user.is_admin?
    	@transactions = Transaction.complete
			respond_to do |format|
				format.csv { send_data @transactions.to_csv }
				format.xls # { send_data @products.to_csv(col_sep: "\t") }
			end
    end
  end

  def toapprove
    if current_user.is_admin?
    	@transactions = Transaction.to_approve
			respond_to do |format|
				format.csv { send_data @transactions.to_csv }
				format.xls # { send_data @products.to_csv(col_sep: "\t") }
			end
    end
  end

  def rejected
    if current_user.is_admin?
    	@transactions = Transaction.rejected
			respond_to do |format|
				format.csv { send_data @transactions.to_csv }
				format.xls # { send_data @products.to_csv(col_sep: "\t") }
			end
    end
  end

  def accepted
    if current_user.is_admin?
    	@transactions = Transaction.accepted
			respond_to do |format|
				format.csv { send_data @transactions.to_csv }
				format.xls # { send_data @products.to_csv(col_sep: "\t") }
			end
    end
  end

  def incomplete
    if current_user.is_admin?
    	@transactions = Transaction.incomplete
			respond_to do |format|
				format.csv { send_data @transactions.to_csv }
				format.xls # { send_data @products.to_csv(col_sep: "\t") }
			end
    end
  end

  #TODO: Add pagination
  def search
    if !params[:q].blank?
      clear_boolean(params[:q], :accepted_eq)
      clear_boolean(params[:q], :rejected_eq)
    end

    if !ransack_parameter[:q].blank?
      @transact_less_than = ransack_parameter[:q][:transactiontime_lteq] if !ransack_parameter[:q][:transactiontime_lteq].blank?
      @transact_great_than = ransack_parameter[:q][:transactiontime_gteq] if !ransack_parameter[:q][:transactiontime_gteq].blank?
    end

    @search = Transaction.ransack(ransack_parameter[:q])
    @transactions = @search.result(distinct: true).includes(:seller, :buyer)
    
    respond_to do |format|
        format.html
        format.csv { send_data @transactions.to_csv({}, true), :type => 'text/csv; header=present', :filename => 'dump.csv' }
        format.xls # { send_data @products.to_csv(col_sep: "\t") }
    end
  end

  private

  #TODO: Move to model method
  def create_Base64_image(picture)
    base64_image = Base64.strict_encode64(picture.read)
    base64_image.strip!
    image = 'data:'+ picture.content_type + ';base64,' + base64_image
    return image
  end

  def create_fake_user(user_email)
    user = User.new
    user.email = user_email + '@alphaplus.com'
    user.password = "DEMOPASSWORD"
    user.name = user_email
    user.save!
    user
  end

  def clear_boolean(q, condition)
    q.delete(condition) if q[condition] == "0"
  end

  def ransack_parameter
    params.permit(:q => [:seller_email_eq, :buyer_email_eq, :accepted_eq, :rejected_eq, :transactiontime_gteq, :transactiontime_lteq])
  end

end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/views/transactions/_gallery.html.erb
<div class="row content-margin">
	<div class="col-sm-12 col-md-12 col-lg-12">
		<h3>Gallery</h3>
		<figure class="figure col-md-2 col-lg-2 offset-md-1">
      		<a class="image-test" href=<%= transaction_image(transaction.id, 'pictureOriginal', transaction.pictureOriginal, false) %> title="Seller Pic">
  				<img src=<%= transaction_image(transaction.id, 'pictureOriginal', transaction.pictureOriginal, true) %> class="figure-img img-fluid img-thumbnail" alt="A generic square placeholder image with rounded corners in a figure.">
  			</a>
  			<figcaption class="figure-caption">Seller Original Picture.</figcaption>
		</figure>

		<figure class="figure col-md-2 col-lg-2">
      		<a class="image-test" href=<%= transaction_image(transaction.id, 'pictureBW', transaction.pictureBW, false) %> title="Buyer Pic">
  				<img src=<%= transaction_image(transaction.id, 'pictureBW', transaction.pictureBW, true) %> class="figure-img img-fluid img-thumbnail" alt="A generic square placeholder image with rounded corners in a figure.">
  			</a>
  			<figcaption class="figure-caption">Buyer Original picture.</figcaption>
		</figure>
    
		<figure class="figure col-md-2 col-lg-2">
      		<a class="image-test" href=<%= transaction_image(transaction.id, 'share1', transaction.share1, false) %> title="Share n°1">
  				<img src=<%= transaction_image(transaction.id, 'share1', transaction.share1, true) %> class="figure-img img-fluid img-thumbnail" alt="A generic square placeholder image with rounded corners in a figure.">
  			</a>
  			<figcaption class="figure-caption">Share n°1 of the transaction.</figcaption>
		</figure>

		<figure class="figure col-md-2 col-lg-2">
      		<a class="image-test" href=<%= transaction_image(transaction.id, 'share2', transaction.share2, false) %> title="Share n°2">
  				<img src=<%= transaction_image(transaction.id, 'share2', transaction.share2, true) %> class="figure-img img-fluid img-thumbnail" alt="A generic square placeholder image with rounded corners in a figure.">
  			</a>
  			<figcaption class="figure-caption">Share n°2 of the transaction.</figcaption>
		</figure>
    
		<figure class="figure col-md-2 col-lg-2">
      		<a class="image-test" href=<%= transaction_image(transaction.id, 'recreatedPic', transaction.recreatedPic, false) %> title="Recreated Pic">
  				<img src=<%= transaction_image(transaction.id, 'recreatedPic', transaction.recreatedPic, true) %> class="figure-img img-fluid img-thumbnail" alt="A generic square placeholder image with rounded corners in a figure.">
  			</a>
  			<figcaption class="figure-caption">Recreated Pic.</figcaption>
		</figure>

	</div>
</div>

app/views/transactions/accepted.xls.erb
<%= render "table" %>

app/views/transactions/all.xls.erb
<%= render "table" %>

app/views/transactions/edit.html.erb
<div class="row">
  <div class="col-sm-12 col-md-12 col-lg-12">
    <h1>Edit Transaction</h1>
    
    <%= form_for(@transaction, url: transaction_update_path(@transaction), html: {class: 'col-sm-12 col-md-6 col-lg-6 offset-md-3 offset-lg-3 content-margin'}) do |f| %>

      <div class="form-group">
        <%= f.label :seller_email %><br />
        <%= f.text_field :seller_email, value: @transaction.try(:seller).try(:email), autofocus: true, class: 'form-control', disabled: true %>
      </div>

      <div class="form-group">
        <%= f.label :buyer_email %><br />
        <%= f.text_field :seller_name, value: @transaction.try(:buyer).try(:email), autofocus: true, class: 'form-control', disabled: true %>
      </div>

      <div class="form-group">
        <%= f.label :timestamp %><br />
        <%= f.text_field :timestamp, value: transaction_time(@transaction.try(:transactiontime)), autofocus: true, class: 'form-control', disabled: true %>
      </div>

      <div class="form-group">
        <%= f.label :amount %><br />
        <%= f.number_field :amount, value: @transaction.try(:amount), min: 0.01, autofocus: true, class: 'form-control', :step => 0.01 %>
      </div>


      <div class="form-group">
        <%= f.submit "Save", class: 'btn btn-primary pull-xs-right edit-button' %>
      </div>
    <% end %>
    </div>

	</div>

  <%= render partial: 'gallery', locals: {transaction: @transaction} %>

</div>

app/views/transactions/index.html.erb
<div class="row">
	<div class="col-md-12 col-sm-12 col-lg-12"><h1>Transactions</h1></div>
	<div class="col-sm-12 col-md-12 col-lg-12">
		<!-- Nav tabs -->
		<ul class="nav nav-tabs" id="nav-admin" role="tablist">
		  <li class="nav-item">
		    <a class="nav-link active" data-toggle="tab" data-val="allTransactions" href="#all-transaction" role="tab">All</a>
		  </li>
		  <li class="nav-item">
		    <a class="nav-link" data-toggle="tab" data-val="toapprove" href="#home" role="tab">To Approve</a>
		  </li>
		  <li class="nav-item">
		    <a class="nav-link" data-toggle="tab" data-val="rejected" href="#rejected" role="tab">Rejected</a>
		  </li>
		  <li class="nav-item">
		    <a class="nav-link" data-toggle="tab" data-val="accepted" href="#accepted" role="tab">Accepted</a>
		  </li>
		  <li class="nav-item">
		    <a class="nav-link" data-toggle="tab" data-val="incomplete" href="#incomplete" role="tab">Incomplete</a>
		  </li>
		</ul>
		
		<!-- Tab panes -->
		<div class="tab-content">
		  <div class="tab-pane fade in active" id="all-transaction" role="tabpanel">
		  	<p class="pull-xs-right">
  				Download:
  				<%= link_to "CSV", transactions_all_path(format: "csv") %> |
  				<%= link_to "Excel", transactions_all_path(format: "xls") %>
			</p>
		  	<table id="allTransaction" class="display table table-striped hover" cellspacing="0" width="100%" data-source="<%= transactions_transactions_path(status: 'ALL', format: :json) %>">
		        <thead>
		            <tr>
		                <th>Id</th>
		                <th>Seller</th>
		                <th>Buyer</th>
		                <th>Timestamp</th>
		                <th>Amount</th>
		            </tr>
		        </thead>
		        <tfoot>
		            <tr>
		                <th>Id</th>
		                <th>Seller</th>
		                <th>Buyer</th>
		                <th>Timestamp</th>
		                <th>Amount</th>
		            </tr>
		        </tfoot>
			</table>
		  </div>
		  <div class="tab-pane fade in" id="home" role="tabpanel">
		  	<p class="pull-xs-right">
  				Download:
  				<%= link_to "CSV", transactions_toapprove_path(format: "csv") %> |
  				<%= link_to "Excel", transactions_toapprove_path(format: "xls") %>
			</p>
		  	<table id="toapprove" class="display table table-striped hover" cellspacing="0" width="100%" data-source="<%= transactions_transactions_path(status: 'TO_APPROVE', format: :json) %>">
		        <thead>
		            <tr>
		                <th>Id</th>
		                <th>Seller</th>
		                <th>Buyer</th>
		                <th>Timestamp</th>
		                <th>Amount</th>
		            </tr>
		        </thead>
		        <tfoot>
		            <tr>
		                <th>Id</th>
		                <th>Seller</th>
		                <th>Buyer</th>
		                <th>Timestamp</th>
		                <th>Amount</th>
		            </tr>
		        </tfoot>
			</table>
		  </div>
		  <div class="tab-pane fade" id="rejected" role="tabpanel">
		  	<p class="pull-xs-right">
  				Download:
  				<%= link_to "CSV", transactions_rejected_path(format: "csv") %> |
  				<%= link_to "Excel", transactions_rejected_path(format: "xls") %>
			</p>
		  	<table id="rejected-table" class="display table table-striped hover" cellspacing="0" width="100%" data-source="<%= transactions_transactions_path(status: 'REJECTED', format: :json) %>">
		        <thead>
		            <tr>
		                <th>Id</th>
		                <th>Seller</th>
		                <th>Buyer</th>
		                <th>Timestamp</th>
		                <th>Amount</th>
		            </tr>
		        </thead>
		        <tfoot>
		            <tr>
		                <th>Id</th>
		                <th>Seller</th>
		                <th>Buyer</th>
		                <th>Timestamp</th>
		                <th>Amount</th>
		            </tr>
		        </tfoot>
			</table>
		  </div>
		  <div class="tab-pane fade" id="accepted" role="tabpanel">
		  	<p class="pull-xs-right">
  				Download:
  				<%= link_to "CSV", transactions_accepted_path(format: "csv") %> |
  				<%= link_to "Excel", transactions_accepted_path(format: "xls") %>
			</p>
		  	<table id="accepted-table" class="display table table-striped hover" cellspacing="0" width="100%" data-source="<%= transactions_transactions_path(status: 'ACCEPTED', format: :json) %>">
		        <thead>
		            <tr>
		                <th>Id</th>
		                <th>Seller</th>
		                <th>Buyer</th>
		                <th>Timestamp</th>
		                <th>Amount</th>
		            </tr>
		        </thead>
		        <tfoot>
		            <tr>
		                <th>Id</th>
		                <th>Seller</th>
		                <th>Buyer</th>
		                <th>Timestamp</th>
		                <th>Amount</th>
		            </tr>
		        </tfoot>
			</table>
		  </div>
		  <div class="tab-pane fade" id="incomplete" role="tabpanel">
		  	<p class="pull-xs-right">
  				Download:
  				<%= link_to "CSV", transactions_incomplete_path(format: "csv") %> |
  				<%= link_to "Excel", transactions_incomplete_path(format: "xls") %>
			</p>
		  	<table id="incomplete-table" class="display table table-striped hover" cellspacing="0" width="100%" data-source="<%= transactions_transactions_path(status: 'INCOMPLETE', format: :json) %>">
		        <thead>
		            <tr>
		                <th>Id</th>
		                <th>Seller</th>
		                <th>Buyer</th>
		                <th>Timestamp</th>
		                <th>Amount</th>
		            </tr>
		        </thead>
		        <tfoot>
		            <tr>
		                <th>Id</th>
		                <th>Seller</th>
		                <th>Buyer</th>
		                <th>Timestamp</th>
		                <th>Amount</th>
		            </tr>
		        </tfoot>
			</table>
		  </div>
		</div>
	</div>
</div>

app/views/transactions/show.html.erb
<div class="row">
  <div class="col-sm-12 col-md-12 col-lg-12"><h1>Transaction</h1></div>
  <% if current_user.is_admin? %>
    <div class="col-sm-12 col-md-12 col-lg-12"><%= link_to "Edit", transaction_edit_path(:id => @transaction.try(:id)), class: 'btn btn-outline-success pull-xs-right edit-button' %></div>
  <% end %>
	<div class="col-sm-4 col-md-4 col-lg-4">
		<div class="card card-block">
      		<h3 class="card-title">Seller</h3>
      		<p class="card-text"><strong>Name:</strong><span class="pull-xs-right"> <%= @transaction.seller.try(:name) %></span></p>
      		<p class="card-text"><strong>Surname:</strong><span class="pull-xs-right"> <%= @transaction.seller.try(:surname) %></span></p>
      		<p class="card-text"><strong>Email:</strong><span class="pull-xs-right"> <%= @transaction.seller.try(:email) %></span></p>
        <% if !@transaction.seller.blank? %>
      		<%= link_to "User Page", user_show_path(:id => @transaction.seller.try(:id)), class: 'btn btn-primary pull-xs-right' %>
        <% end %>
    	</div>
	</div>
	<div class="col-sm-4 col-md-4 col-lg-4">
		<div class="card card-block">
      		<h3 class="card-title">Buyer</h3>
      		<p class="card-text"><strong>Name:</strong><span class="pull-xs-right"> <%= @transaction.buyer.try(:name) %></span></p>
      		<p class="card-text"><strong>Surname:</strong><span class="pull-xs-right"> <%= @transaction.buyer.try(:surname) %></span></p>
      		<p class="card-text"><strong>Email:</strong><span class="pull-xs-right"> <%= @transaction.buyer.try(:email) %></span></p>
        <% if !@transaction.buyer.blank? %>
      		<%= link_to "User Page", user_show_path(:id => @transaction.buyer.try(:id)), class: 'btn btn-primary pull-xs-right' %>
        <% end %>
		</div>
	</div>
	<div class="col-sm-4 col-md-4 col-lg-4">
		<div class="card card-block">
      		<h3 class="card-title">Info</h3>
      		<p class="card-text"><strong>Amount: </strong><span class="pull-xs-right"> <%= number_to_currency(@transaction.amount) %></span></p>
      		<p class="card-text"><strong>Timestamp: </strong><span class="pull-xs-right"> <%= transaction_time(@transaction.transactiontime) %></span></p>
      		<p class="card-text"><strong>Status: </strong> <%= status(@transaction) %></p>
      	<% if current_user.is_admin? %>
      		<% if @transaction.is_completed? %>
      			<% if @transaction.is_accepted? %>
      				<%= link_to "Accept", transaction_accept_path(:id => @transaction.id), class: 'btn btn-success pull-xs-left disabled' %>
      				<%= link_to "Reject", transaction_reject_path(:id => @transaction.id), class: 'btn btn-danger pull-xs-right' %>
      			<% elsif @transaction.is_rejected? %>
      				<%= link_to "Accept", transaction_accept_path(:id => @transaction.id), class: 'btn btn-success pull-xs-left' %>
      				<%= link_to "Reject", transaction_reject_path(:id => @transaction.id), class: 'btn btn-danger pull-xs-right disabled' %>
      			<% else %>
      				<%= link_to "Accept", transaction_accept_path(:id => @transaction.id), class: 'btn btn-success pull-xs-left' %>
      				<%= link_to "Reject", transaction_reject_path(:id => @transaction.id), class: 'btn btn-danger pull-xs-right' %>
      			<% end %>
      		<% end %>
      	<% end %>
		</div>
	</div>
</div>

<%= render partial: 'gallery', locals: {transaction: @transaction} %>