config/routes.rb
Rails.application.routes.draw do

  use_doorkeeper
  devise_for :users

  namespace :api do
  	namespace :v1 do
  		resources :users, only: [:index, :update]
  		post '/users/prova' => 'users#prova'
  		post '/transactions/sell' => 'transactions#sell'
  		post '/transactions/buy' => 'transactions#buy'
    	post :signup, to: 'signup#index'
  	end
  end

  match "/404", :to => "errors#not_found", :via => :all
  match "/500", :to => "errors#internal_server_error", :via => :all

  get 'transactions/index' => 'transactions#index'
  get 'transactions/transactions' => 'transactions#transactions'
  get 'transactions' => 'transactions#index'

  get 'transactions/search' => 'transactions#search', as: :transactions_search #used by the ransack page

  get 'users/index' => 'users#index', as: :users_index
  get 'users/all' => 'users#all_users', as: :users_all

  get 'user/all_transactions' => 'users#all_transactions', as: :user_transactions
  get 'user/purchases' => 'users#purchases', as: :user_purchases
  get 'user/sales' => 'users#sales', as: :user_sales
  get 'user/search' => 'users#search', as: :user_search

  get 'user/download_sells' => 'users#by_seller', as: :user_sells
  get 'user/download_purchases' => 'users#by_buyer', as: :user_buys
  get 'user/download_all' => 'users#all', as: :user_alltransactions

  get 'user/:id' => 'users#show', as: :user_show
  
  get 'transactions/accept/:id' => 'transactions#accept', as: :transaction_accept
  get 'transactions/reject/:id' => 'transactions#reject', as: :transaction_reject
  post 'transactions/create' => 'transactions#create', as: :transaction_create
  get 'transactions/upload' => 'transactions#upload', as: :transaction_upload

  get 'transactions/all' => 'transactions#all', as: :transactions_all
  get 'transactions/toapprove' => 'transactions#toapprove', as: :transactions_toapprove
  get 'transactions/rejected' => 'transactions#rejected', as: :transactions_rejected
  get 'transactions/accepted' => 'transactions#accepted', as: :transactions_accepted
  get 'transactions/incomplete' => 'transactions#incomplete', as: :transactions_incomplete


  get 'transactions/:id' => 'transactions#show', as: :transaction_show
  get 'transactions/:id/edit' => 'transactions#edit', as: :transaction_edit
  match 'transactions/:id/update' => 'transactions#update', as: :transaction_update, :via => [:post, :patch]

  get "/uploads/transaction/:mount/example/:id/:basename.:extension", :controller => "images", :action => "download"

  authenticated :user do
    root :to => "transactions#index"
  end

  unauthenticated :user do
    devise_scope :user do
      get "/" => "devise/sessions#new"
    end
  end

  
end

app/views/layouts/application.html.erb
  <!DOCTYPE html>
  <html>
    <head>
      <title>Selfie4pay</title>
      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
      <meta http-equiv="x-ua-compatible" content="ie=edge">

      <%= csrf_meta_tags %>

      <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
      <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
      <script type="text/javascript">// Immediately after the js include
        Dropzone.autoDiscover = false;
      </script>
    </head>

    <body>
      <nav class="navbar navbar-fixed-top navbar-dark bg-inverse">
        <button class="navbar-toggler hidden-sm-up" type="button" data-toggle="collapse" data-target="#exCollapsingNavbar2" aria-controls="exCollapsingNavbar2" aria-expanded="false" aria-label="Toggle navigation">
      &#9776;
        </button>
        <a class="navbar-brand" href="#">PayWithASelfie</a>

        <% if current_user and current_user.is_admin? %>
        <div class="collapse navbar-toggleable-xs" id="exCollapsingNavbar2">
          
          <ul class="nav navbar-nav">
            <li class="nav-item <%= active_class(transactions_index_path) %>">
              <a class="nav-link" href=<%= transactions_index_path %> >Transactions <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item <%= active_class(users_index_path) %>">
              <a class="nav-link" href=<%= users_index_path %> >Users</a>
            </li>
            <li class="nav-item <%= active_class(transaction_upload_path) %>">
              <a class="nav-link" href=<%= transaction_upload_path %> >Uploads</a>
            </li>
            <li class="nav-item <%= active_class(transactions_search_path) %>">
              <a class="nav-link" href=<%= transactions_search_path %> >Export</a>
            </li>
          </ul>

          <ul class="nav navbar-nav pull-xs-right">
          <% if current_user.blank? %>
            <%= link_to 'Log In', new_user_session_path, class: "btn btn-outline-primary pull-xs-right" %>
          <% else %>
          <li class="nav-item">
            <%= link_to current_user.full_name, user_show_path(current_user), class: "nav-link #{active_class(user_show_path(current_user))}", method: :get  if not current_user.id.blank? %>
          </li>
          <li class="nav-item"><a class="nav-link" href="#"> | </a></li>
          <li class="nav-item">
            <%= link_to 'Log Out', destroy_user_session_path, class: "btn btn-outline-primary pull-xs-right", method: :delete %>
          </li>
          <% end %>
          </ul>
        </div>
        <% else %>
        <div class="collapse navbar-toggleable-xs" id="exCollapsingNavbar2">
          
          <% if current_user.blank? %>
            <%= link_to 'Log In', new_user_session_path, class: "btn btn-outline-primary pull-xs-right" %>
          <% else %>
            <ul class="nav navbar-nav">
              <li class="nav-item <%= active_class(user_show_path(current_user)) %>">
                <a class="nav-link" href=<%= user_show_path %> >User <span class="sr-only">(current)</span></a>
              </li>
            </ul>
            <ul class="nav navbar-nav pull-xs-right">
              <li class="nav-item">
              <%= link_to current_user.full_name, user_show_path(current_user), class: "nav-link #{active_class(user_show_path(current_user))}", method: :get %>
              </li>
              <li class="nav-item"><a class="nav-link" href="#"> | </a></li>
              <li class="nav-item">
               <%= link_to 'Log Out', destroy_user_session_path, class: "btn btn-outline-primary pull-xs-right", method: :delete %>
              </li>
            </ul>
          <% end %>
        </div>
        <% end %>
      </nav>
      <div class="container">
        <div class="row">
          <div class="col-sm-12 col-lg-12">
            <% unless notice.blank? %>
              <div class="alert alert-info alert-dismissible fade in" role="alert">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
                </button><%= notice %>
              </div> 
            <% end %>
            <% unless alert.blank? %>
              <div class="alert alert-danger alert-dismissible fade in" role="alert">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
                </button><%= alert %>
              </div>
            <% end %>
          </div>
        </div>
        <%= yield %>
      </div>
    </body>
  </html>